<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>8ee793cc-8438-42c9-9a51-85c32ca2b50a</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.9"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.9">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.OpenApi" Version="2.7.5"/>
    </ItemGroup>

    <ItemGroup>
        <Content Update="appsettings.Development.json">
            <DependentUpon>appsettings.json</DependentUpon>
        </Content>
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\GeoStrike.Application\GeoStrike.Application.csproj"/>
        <ProjectReference Include="..\GeoStrike.Domain.Catalog\GeoStrike.Domain.Catalog.csproj"/>
        <ProjectReference Include="..\GeoStrike.Domain\GeoStrike.Domain.csproj"/>
        <ProjectReference Include="..\GeoStrike.Infrastructure\GeoStrike.Infrastructure.csproj"/>

        <ProjectReference Include="..\..\Shared\GeoStrike.Communication\GeoStrike.Communication.csproj"/>
        <ProjectReference Include="..\..\Shared\GeoStrike.Exception\GeoStrike.Exception.csproj"/>
    </ItemGroup>

</Project>