@Host = https://localhost:7169

### Iniciar a evolução de um edifício
POST {{Host}}/Building
Content-Type: application/json

{
  "id": "e3b0c442-98fc-1c14-9afb-f4c8996fb924",
  "completionDate": "2026-07-06T16:00:00Z"
}