@Host = https://localhost:7200

### Iniciar a evolução de um edifício
POST {{Host}}/Building
Content-Type: application/json

{
  "playerId": "41D3A083-4137-439A-8688-B9C6F6A9AB8C",
  "buildingId": "CDEAFBCE-68B1-4127-940A-A6211B1A43D7"
}