<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\GeoStrike.Domain\GeoStrike.Domain.csproj"/>
        <EmbeddedResource Include="StaticData\buildings.json">
            <LogicalName>GeoStrike.Domain.Catalog.StaticData.buildings.json</LogicalName>
        </EmbeddedResource>
    </ItemGroup>

</Project>
