// <auto-generated />
using System;
using GeoStrike.Infrastructure.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GeoStrike.Infrastructure.Migrations
{
    [DbContext(typeof(GeoStrikeDbContext))]
    [Migration("20260709201308_SomeMigrationThatIDontKnowWhatItIs2")]
    partial class SomeMigrationThatIDontKnowWhatItIs2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GeoStrike.Domain.Entities.Building", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("ConstructionCost")
                        .HasColumnType("float");

                    b.Property<short>("StartLevel")
                        .HasColumnType("smallint");

                    b.Property<byte>("Type")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.ToTable("Buildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cdeafbce-68b1-4127-940a-a6211b1a43d7"),
                            ConstructionCost = 0.0,
                            StartLevel = (short)1,
                            Type = (byte)0
                        },
                        new
                        {
                            Id = new Guid("b9336dd7-cfaa-4b03-a0b3-d46af7a94b96"),
                            ConstructionCost = 100.0,
                            StartLevel = (short)1,
                            Type = (byte)1
                        });
                });

            modelBuilder.Entity("GeoStrike.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Gold")
                        .HasColumnType("int");

                    b.Property<double>("Money")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Oil")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = new Guid("41d3a083-4137-439a-8688-b9c6f6a9ab8c"),
                            Gold = 5000000,
                            Money = 5000000.0,
                            Name = "John Doe",
                            Oil = 5000000
                        });
                });

            modelBuilder.Entity("GeoStrike.Domain.Entities.PlayerBuilding", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuildingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Level")
                        .HasColumnType("int");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("PlayerId");

                    b.ToTable("PlayerBuildings");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3cd60eca-d0ce-4f25-8501-938b1e07ecbb"),
                            BuildingId = new Guid("cdeafbce-68b1-4127-940a-a6211b1a43d7"),
                            Level = 2,
                            PlayerId = new Guid("41d3a083-4137-439a-8688-b9c6f6a9ab8c"),
                            Quantity = 1
                        },
                        new
                        {
                            Id = new Guid("4a99048b-403e-417b-8efa-943322e46816"),
                            BuildingId = new Guid("b9336dd7-cfaa-4b03-a0b3-d46af7a94b96"),
                            Level = 1,
                            PlayerId = new Guid("41d3a083-4137-439a-8688-b9c6f6a9ab8c"),
                            Quantity = 1
                        });
                });

            modelBuilder.Entity("GeoStrike.Domain.Entities.PlayerBuilding", b =>
                {
                    b.HasOne("GeoStrike.Domain.Entities.Building", "Building")
                        .WithMany()
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("GeoStrike.Domain.Entities.Player", "Player")
                        .WithMany("Buildings")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");

                    b.Navigation("Player");
                });

            modelBuilder.Entity("GeoStrike.Domain.Entities.Player", b =>
                {
                    b.Navigation("Buildings");
                });
#pragma warning restore 612, 618
        }
    }
}
