name: GeoStrike CI

on:
  push:
    branches: [ "main", "develop" ]
  pull_request:
    branches: [ "main", "develop" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4
      
      - name: Configurar .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'
      
      - name: Restaurar dependências
        run: dotnet restore
      
      - name: Compilar (Build)
        run: dotnet build --no-restore --configuration Release
      
      - name: Executar Testes Unitários
        run: dotnet test --no-build --configuration Release --verbosity normal